<a href="https://colab.research.google.com/github/stroboskop/data-sience-bootcamp/blob/main/01_wprowadzenie/intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

np.__version__



'1.19.5'

# Tablice 2d i 3d

In [ ]:
x = np.array([1,3])
print(x)

x.ndim
x.shape
x.size

x = np.array([1.3, 2.3, 1.4])


x = np.array([[1,2], [-3,1]])
print(x.shape)

x = np.array([[1,2,4] , [4,2,1]])
print(x.shape)

//

[1 3]
(2, 2)
(2, 3)


In [ ]:
#3d arrays
x = np.array(
    [[[4, 3, 1],
      [3, 1, 2]],
     
      [[4, 1, 3],
       [4, 2, 1]]]
)

print(x.ndim)
print(x.shape)

3
(2, 2, 3)


Typy danych

In [ ]:
#ustalanie datypu tahblicy
A = np.array([1, 2, 3], dtype='float')



# Tworzenie tablic


In [ ]:
np.zeros(shape=(4, 10), dtype='int')

#tworzy tablice 4x10 wypełnioną 0, domyslnie we float
np.zeros(shape=(4, 10))

#tworzy tablice 4x10 wypełnioną 1
np.ones(shape=(4, 10))

#tworzy tablice 3x3 wypełnioną 4
np.full(shape=(3, 3), fill_value=4)

#to jak range(10)
np.arange(10)

#to jak range(10)
np.arange(start= 10, stop=100, step=10)

#to jak range(10)
np.arange(start= 100, stop=10, step=-10)

#popobne do arrane num   mówi ile będzie elementów, będę równo rozłożone
np.linspace(start=0, stop=1, num=10)

A = np.arange(15)
A

A = A.reshape((3, 5))
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

# Podstawowe operacje na tablicach

In [4]:
A = np.array([3, 1, 4, 2])
B = np.array([3, -1, 3, 2])

print(A)
print(B)


#są to metody równorzędne
A + B
np.add(A, B)

A - B
np.subtract(A, B)

A * B
np.multiply(A, B)

A / B
np.divide(A, B)

A + 3

#mnożenie macierzowe np.dot
x = np.array([[1, 3], [-2, 0]])
y = np.array([[6, 0], [-1, 2]])

np.dot(x, y)

x @ y

[3 1 4 2]
[ 3 -1  3  2]


array([[  3,   6],
       [-12,   0]])

# Generowanie liczb pseudolosowych

In [21]:
#określenie seed dla generatora
np.random.seed(0)

#zwraca nam tablicę 10 x 4 losowych liczb (przez to, że określono seed nie są one naprawdę losowe)
#z przedziału normalnego
np.random.randn(10, 4)

#rozkład jednostajny na przedziale
np.random.rand()

#zwraca tablicę 10 elementową
np.random.rand(10)

#zwraca liczę całkowitą mniejszą od 10 i większa od zera
np.random.randint(10)

np.random.randint(low=10, high=101, size=10)

#zwraca losowy przekazany element
np.random.choice([4, 2, 1, 4])

np.random.choice(['python', 'java', 'sql', 'c++'])

data = np.arange(10)
data

#przetasowany obiekt
np.random.shuffle(data)
data

array([3, 9, 7, 8, 6, 4, 2, 1, 0, 5])

# Podstawowe funkcje w bibliotece numpy

In [31]:
#exponent
np.exp(1)

#pierwiastek
np.sqrt(9)

#bada czy wartość logiczną false i true, 
#jeśli który kolwiek obiekt zwraca false to ta też zwróci
np.all([2, 3, 1, 0, 1])

#zwraca odwrotnie do all
np.any([1, 2, 1])

A = np.random.rand(5)
print(A)

#zwraca największa numer elementu tablicy o największej wartość
np.argmax(A)

A[np.argmax(A)]

#zwraca największa numer elementu tablicy o najmniejszej wartość
np.argmin(A)

#sortuje elementy w tablicy, zwraca tablicę z numerami elementów
np.argsort(A)

#zwraca faktyczną maksymalną wartość
np.max(A)

#zwraca faktyczną minimalną wartość
np.min(A)

#zwraca średnią wartość
np.mean(A)

#mediana
np.median(A)

#odchylenie standardowe
np.std(A)

[0.66741038 0.13179786 0.7163272  0.28940609 0.18319136]


0.7163272041185655

# Iteracja po tablicach, zmiana rozmiaru oraz maski logiczne

In [50]:
#iteracja po każdym elemencie tablicy
A = np.arange(20)

A = A.reshape(5,4)
A

#wypłaszcza dane
A.ravel

#transponowanie
A.T

A = np.arange(start=-10, stop=10, step=0.5)
A = A.reshape(10, -1)
A

#zwraca maskę logiczną, gdzie wystepują wartości większe od 0
A > 0

#zwroci tablicę która posiada jedynie wartości większe od 0
A[A > 0]

#dla kilku warunków nie działa A[A > 0 and A < 5], należy:
A[np.bitwise_and(A > - 5, A < 5)]


array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])